packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@playwright/test": 1.58.2
  "@sveltejs/package": ^2.5.7
  "@sveltejs/vite-plugin-svelte": ^7.0.0
  "@types/node": ^24
  "@typescript/native-preview": "7.0.0-dev.20260316.1"
  "@svar-ui/core-locales": "2.5.0"
  "@svar-ui/lib-data-provider": "1.7.2"
  "@svar-ui/lib-dom": "0.12.1"
  "@svar-ui/lib-state": "1.9.6"
  "@svar-ui/svelte-comments": "2.5.0"
  "@svar-ui/svelte-core": "2.5.0"
  "@svar-ui/svelte-editor": "2.5.0"
  "@svar-ui/svelte-filter": "2.5.0"
  "@svar-ui/svelte-layout": "2.5.0"
  "@svar-ui/svelte-menu": "2.5.0"
  "@svar-ui/svelte-tasklist": "2.5.0"
  "@svar-ui/svelte-toolbar": "2.5.0"
  playwright: 1.58.2
  rollup-plugin-visualizer: ^7.0.1
  sharp: ^0.34.5
  svelte: ^5.54.0
  svelte-check: ^4.4.6
  svelte-spa-router: ^5.0.0
  "typescript": "^5.9.3"
  vite: npm:@voidzero-dev/vite-plus-core@0.1.16
  vite-plus: 0.1.16
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.16

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
